# Generated by Django 2.2.dev20181005132628 on 2018-10-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='DataDeNascimento',
        ),
    ]
